### ISSUE TITLE
Table is not working with toggle menu

### ISSUE THREAD

**Issue by sariogluba** [t-edson/bootstable#12]
Also, there is a type error in safari browser.

TypeError: params.$addColButton.click is not a function. (In 'params.$addColButton.click(function() {
            rowAddNewCol($tabedi.attr("id"));
        })', 'params.$addColButton.click' is undefined)

**Comment by t-edson** [comment]
Sorry. I cannot check code by now, because of quarantine.

**Comment by t-edson** [comment]
I verified the error. It's because of the last changes done for a colaborator. It's working now.
