### ISSUE TITLE
Duplicate buttons on each row

### ISSUE THREAD

**Issue by kelvink96** [t-edson/bootstable#13]
I have an issue when using bootstable, the edit and delete buttons are appearing twice on each row. 
See image below.

![bootstable issue](https://user-images.githubusercontent.com/26582923/87159104-7677d000-c2c9-11ea-91b1-df711595dab9.png)

**Comment by RiLaRos** [comment]
Hello @kelvink96,

The buttons appear when you call to .SetEditable(), check if you only call once this function.

Regards!
