### ISSUE TITLE
Is posible get data and send to json object ?

### ISSUE THREAD

**Issue by enrutador** [t-edson/bootstable#3]
Hi Very nice Job congratulations ¡¡¡¡

I like to use your  bootstable.min.js code. But i have one doubt , bootstrap-table.min.js have a function to get all the values in a table, and then can send all the values to a json object ($table.bootstrapTable('getData') ), its posible do a similar function compatible with your code ?

```
 $Guardadatos.click(function () {
  	 // alert(JSON.stringify($table.bootstrapTable('getData')));
  	  var datos = JSON.stringify($table.bootstrapTable('getData'));
  	  //var obj=JSON.parse(datos);
        var obj = jQuery.parseJSON(datos);
        console.log(obj);
        
    });
```
Thanks

**Comment by t-edson** [comment]
Hi. I also think a function like that is needed in Bootstable. I remember I did some similar but using CSV. I will consider to include this function. Anyway collaborations are welcome.

**Comment by DjovDev** [comment]
Same would be nice for edited / added / deleted row.

We need the event listeners to notify what exactly changed. Great project so far.

**Comment by t-edson** [comment]
> I like to use your bootstable.min.js code. But i have one doubt , bootstrap-table.min.js have a function to get all the values in a table, and then can send all the values to a json object ($table.bootstrapTable('getData') ), its posible do a similar function compatible with your code ?

A function is included in the library to export HTML tables to JSON: TableToJson()

Check the version 1.3.

**Comment by t-edson** [comment]
> Same would be nice for edited / added / deleted row.
> 
> We need the event listeners to notify what exactly changed. Great project so far.

New events are included in the last version.
