### ISSUE TITLE
Adding row not showing editable inputs

### ISSUE THREAD

**Issue by DjovDev** [t-edson/bootstable#4]
Creating a button and then adding $addButton: $('#but_add') to the params does work well when creating a new row. But shouldn't it transfer the new (now empty) row into input boxes directly?

**Comment by t-edson** [comment]
I see. Probably it's not a good behaviour. Maybe it's something simple to modify but currently I'm dedicated to another project in Object Pascal and not working in Javascript.  I will try to fix when review this library.

**Comment by t-edson** [comment]
Version 1.3 have a new functions to add rows: rowAddNewAndEdit(). It add a new row and set to edition mode, putting the focus in the first column.
You can set initial values too.
