### ISSUE TITLE
How to avoid a row to be edited

### ISSUE THREAD

**Issue by Jibeji** [t-edson/bootstable#5]
Hi,
Nice job, exactly what I was looking for. Thanks a lot.

Is it possible to avoid some rows to be edited ?

**Comment by t-edson** [comment]
Hi.

Current version doesn't allow to protect row for editing. I will consider for new versions.

**Comment by t-edson** [comment]
To protect a row to be edited, you could modify the function butRowEdit() and add a verification, something about an attribute like class or name. Then to protect rows just have to change that attribute.
